// Metadata
import type { Metadata } from "next";

// Font
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

// Styled-Components config
import StyledComponentsRegistry from './lib/registry';
import GlobalStyles from "@/styles/GlobalStyles";
import theme from "@/styles/theme";
import { ThemeProvider } from "styled-components";



// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <GlobalStyles />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
